name: Pull Request

on:
  pull_request:

jobs:
  setup:
    defaults:
      run:
        working-directory: client    
    name: Setup client
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
      - name: Install deps
        run: npm ci
        

  lint:
    defaults:
      run:
        working-directory: client    
    name: Lint client
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
      - run: npm ci
      - name: Lint JS and Vue
        run: npm run lint

  test:
    defaults:
      run:
        working-directory: client
    name: Test client
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/New_York"
      - run: npm ci
      - name: Run tests
        run: npm run test:ci

  build:
    defaults:
      run:
        working-directory: client
    name: Build client
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'
      - run: npm ci
      - name: Build app
        run: npm run build
